version: "3.9"
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./database/db:/data/db
      - ./database/config:/data/configdb
    userns_mode: keep-id
    expose:
      - 27017
    ports:
      - 27017:27017
  service:
    build: .
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=5001
      - DB_HOST=db
    depends_on:
      - db
    expose:
      - 5001
    ports:
      - 5001:5001
volumes:
  data:
  config:
